/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SketchRouteImport } from './routes/sketch'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SketchRoute = SketchRouteImport.update({
  id: '/sketch',
  path: '/sketch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sketch': typeof SketchRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sketch': typeof SketchRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sketch': typeof SketchRoute
  '/work': typeof WorkRouteWithChildren
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sketch' | '/work' | '/work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sketch' | '/work' | '/work/$slug'
  id: '__root__' | '/' | '/sketch' | '/work' | '/work/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SketchRoute: typeof SketchRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sketch': {
      id: '/sketch'
      path: '/sketch'
      fullPath: '/sketch'
      preLoaderRoute: typeof SketchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SketchRoute: SketchRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
